In [1]:
import numpy as np
import xarray as xr
import project as P

In [2]:
maskedarea = xr.DataArray(np.ones((10,10)),dims=('x','y'))
x = xr.DataArray(np.random.uniform(0,10,(10,10)),dims=('x','y'))
y = xr.DataArray(np.random.uniform(0,10,(10,10)),dims=('x','y'))

In [5]:
import importlib
importlib.reload(P)
P.rmsd(x,y,dim='x').values

array([3.14506544, 3.63601197, 3.8810039 , 3.77728939, 3.9139084 ,
       5.37351995, 5.20890608, 4.25308291, 5.07499084, 2.61140007])

In [6]:
P.rmsd(x,y,dim='y').values

array([5.43037362, 4.78819293, 3.41920078, 3.7135739 , 4.35106007,
       1.80990286, 3.59151655, 4.46509538, 4.48918513, 4.61933364])

In [7]:
P.rmsd(x,y,dim=['x','y']).values

array(4.17650429)

In [8]:
P.rmsd(x,y).values

array(4.17650429)

In [7]:
%matplotlib inline
import importlib

importlib.reload(P)
mask = P.region_mask(masked_area=True)
mask

<xarray.DataArray (region: 1, nlat: 384, nlon: 320)>
array([[[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]]])
Coordinates:
  * region   (region) <U7 'CalCOFI'
    TLAT     (nlat, nlon) float64 -79.22 -79.22 -79.22 -79.22 -79.22 -79.22 ...
    TLONG    (nlat, nlon) float64 320.6 321.7 322.8 323.9 325.1 326.2 327.3 ...
    ULAT     (nlat, nlon) float64 -78.95 -78.95 -78.95 -78.95 -78.95 -78.95 ...
    ULONG    (nlat, nlon) float64 321.1 322.3 323.4 324.5 325.6 326.8 327.9 ...
Dimensions without coordinates: nlat, nlon

In [8]:
ds = P.open_ann_fosi()
ds

<xarray.Dataset>
Dimensions:          (date: 68, nlat: 144, nlat_G: 384, nlon: 139, nlon_G: 320, nz_G: 60, time: 68)
Coordinates:
  * time             (time) int64 1948 1949 1950 1951 1952 1953 1954 1955 ...
  * date             (date) object 1948-07-16 21:59:59 1949-07-16 21:59:59 ...
Dimensions without coordinates: nlat, nlat_G, nlon, nlon_G, nz_G
Data variables:
    TLAT             (nlat, nlon) float64 ...
    TLONG            (nlat, nlon) float64 ...
    ULAT             (nlat, nlon) float64 ...
    ULONG            (nlat, nlon) float64 ...
    KMT              (nlat, nlon) float64 0.0 0.0 0.0 42.0 42.0 41.0 33.0 ...
    KMU              (nlat, nlon) float64 ...
    DXU              (nlat, nlon) float64 ...
    DYU              (nlat, nlon) float64 ...
    REGION_MASK      (nlat, nlon) float64 ...
    TAREA            (nlat, nlon) float64 3.717e+13 3.717e+13 3.717e+13 ...
    vol3d            (nz_G, nlat_G, nlon_G) float64 ...
    volume_dyn       (nlat, nlon) float64 ...
    volu

In [9]:
importlib.reload(P)
dp = P.open_ann_dple()
dp.time

<xarray.DataArray 'time' (time: 62)>
array([1954., 1955., 1956., 1957., 1958., 1959., 1960., 1961., 1962., 1963.,
       1964., 1965., 1966., 1967., 1968., 1969., 1970., 1971., 1972., 1973.,
       1974., 1975., 1976., 1977., 1978., 1979., 1980., 1981., 1982., 1983.,
       1984., 1985., 1986., 1987., 1988., 1989., 1990., 1991., 1992., 1993.,
       1994., 1995., 1996., 1997., 1998., 1999., 2000., 2001., 2002., 2003.,
       2004., 2005., 2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013.,
       2014., 2015.], dtype=float32)
Coordinates:
  * time     (time) float32 1954.0 1955.0 1956.0 1957.0 1958.0 1959.0 1960.0 ...
Attributes:
    long_name:    ensemble
    description:  historical year corresponding to forecast month 1
    example:      S=1954 for forecasts initialized on November 1 1954

In [3]:
import project as P
import importlib
importlib.reload(P)
ds = P.dataview(forecast_lead=(5,7),apply_region_mask=False)
print(ds['fosi'].time.values)
print(ds['dp'].time.values)

[1960. 1961. 1962. 1963. 1964. 1965. 1966. 1967. 1968. 1969. 1970. 1971.
 1972. 1973. 1974. 1975. 1976. 1977. 1978. 1979. 1980. 1981. 1982. 1983.
 1984. 1985. 1986. 1987. 1988. 1989. 1990. 1991. 1992. 1993. 1994. 1995.
 1996. 1997. 1998. 1999. 2000. 2001. 2002. 2003. 2004. 2005. 2006. 2007.
 2008. 2009. 2010. 2011. 2012. 2013. 2014. 2015.]
[1960. 1961. 1962. 1963. 1964. 1965. 1966. 1967. 1968. 1969. 1970. 1971.
 1972. 1973. 1974. 1975. 1976. 1977. 1978. 1979. 1980. 1981. 1982. 1983.
 1984. 1985. 1986. 1987. 1988. 1989. 1990. 1991. 1992. 1993. 1994. 1995.
 1996. 1997. 1998. 1999. 2000. 2001. 2002. 2003. 2004. 2005. 2006. 2007.
 2008. 2009. 2010. 2011. 2012. 2013. 2014. 2015.]


In [36]:
ds['dp'].time

<xarray.DataArray 'time' (time: 59)>
array([1956.5, 1957.5, 1958.5, 1959.5, 1960.5, 1961.5, 1962.5, 1963.5, 1964.5,
       1965.5, 1966.5, 1967.5, 1968.5, 1969.5, 1970.5, 1971.5, 1972.5, 1973.5,
       1974.5, 1975.5, 1976.5, 1977.5, 1978.5, 1979.5, 1980.5, 1981.5, 1982.5,
       1983.5, 1984.5, 1985.5, 1986.5, 1987.5, 1988.5, 1989.5, 1990.5, 1991.5,
       1992.5, 1993.5, 1994.5, 1995.5, 1996.5, 1997.5, 1998.5, 1999.5, 2000.5,
       2001.5, 2002.5, 2003.5, 2004.5, 2005.5, 2006.5, 2007.5, 2008.5, 2009.5,
       2010.5, 2011.5, 2012.5, 2013.5, 2014.5], dtype=float32)
Coordinates:
  * time     (time) float32 1956.5 1957.5 1958.5 1959.5 1960.5 1961.5 1962.5 ...
Attributes:
    long_name:    ensemble
    description:  historical year corresponding to forecast month 1
    example:      S=1954 for forecasts initialized on November 1 1954

In [3]:
import importlib
importlib.reload(P)



<module 'project' from '/gpfs/u/home/mclong/p/o2-prediction/calcs/project.py'>